### ISSUE TITLE
Display Prime Array Elements (Java)

### ISSUE THREAD

**Issue by aditya109** [aditya109/git-osp-for-beginners#1]
Problem : Write a Program to store 20 numbers in an array and display only those numbers which are prime.

**Comment by rishirajpurohit** [comment]
Hello @aditya109 I would like to work on this issue, does the solution/program has to be in a specific language ?

**Comment by Hinal-Srivastava** [comment]
Hi @aditya109,
I can contribute in Python. Should I?

**Comment by Himith** [comment]
Hey i want to work on this Please assign this to me>>
in python,c++,c or python

**Comment by aryankr2005** [comment]
Hello @aditya109 I am a keen programmer who would like to work on this issue. This is my first time exploring GitHub and open source repositories. Can I work on the java portion?

**Comment by aditya109** [comment]
Hello guys, I did not expect these many people interested many contributions. If you guys can hold on, I have to get this repo and add many more issues for you. Thanks for your patience.

**Comment by Hinal-Srivastava** [comment]
> Hello guys, I did not expect these many people interested many contributions. If you guys can hold on, I have to get this repo and add many more issues for you. Thanks for your patience.

Its HacktoberFest. Contributors are making the best of it😂👍

**Comment by rishirajpurohit** [comment]
Oh I see it was already assigned, best of luck @aryankr2005 , I'll remove my PR

**Comment by rishirajpurohit** [comment]
@aditya109 you can create a issue to add more problems 😉

**Comment by aditya109** [comment]
> Hi @aditya109,
> I can contribute in Python. Should I?

Would you like to work on this issue #4 ?

**Comment by aditya109** [comment]
> Hey i want to work on this Please assign this to me>>
> in python,c++,c or python

Would you like to work on this issue #6 ?

**Comment by Hinal-Srivastava** [comment]
> > Hi @aditya109,
> > I can contribute in Python. Should I?
> 
> Would you like to work on this issue #4 ?

Sure!
