### ISSUE TITLE
[Java] Pass Or Fail

### ISSUE THREAD

**Issue by aditya109** [aditya109/git-osp-for-beginners#102]
Write a program to input an array of names of 20 students who PASSED with online examination. The program should ask for the name of a student and inform whether s/he has PASSED or FAILED. Repeat the process for checking the names till the user enter the name as exit.

**Comment by aryankr2005** [comment]
Hello @aditya109 I am a keen programmer who would like to work on this issue. This is my first time exploring GitHub and open source repositories. Can I work on the java portion?

**Comment by aditya109** [comment]
Hi @aryankr2005 ! Sure please go ahead and resolve this issue. I will assign this issue to you. A humble request to star this repo to encourage further contributions.

**Comment by aryankr2005** [comment]
Thank u for helping me for working in your repository....
