### ISSUE TITLE
[Fibonacci series to be added]    

### ISSUE THREAD

**Issue by lokgubhaju** [aditya109/git-osp-for-beginners#104]
The Fibonacci sequence is a series of numbers where a number is the addition of the last two numbers, starting with 0, and 1.The Fibonacci Sequence: 0, 1, 1, 2, 3, 5, 8, 13, 21, 34, 55…Written as a rule, the expression is:Xn = Xn-1 + Xn-2

**Comment by kritisingh1** [comment]
Hey can I take this up?

**Comment by lokgubhaju** [comment]
You can do it and see which one comes efficient and fast.

**Comment by aditya109** [comment]
> Hey can I take this up?

Hi @kritisingh !  I am sorry I can't this issue has already been claimed, but feel free to raise one and link this issue. I will approve your PR and tag it `hacktoberfest-accepted` which carries the same value and will counted in Hacktoberfest stats. Also a humble request could please star the repo, it helps in encouraging contributions.

**Comment by lokgubhaju** [comment]
Is it fine now? @aditya109
