### ISSUE TITLE
Create a Program that checks if the given password is strong or not. | Python

### ISSUE THREAD

**Issue by Aashrut** [aditya109/git-osp-for-beginners#124]
If the password is strong then it should return True and if the password is not strong enough then it should return False.
Here are the conditions for the password to be strong:
-  Its length is at least 8.
-  It contains at least one digit.
-  It contains at least one lowercase English character.
-  It contains at least one uppercase English character.
-  It contains at least one special character. The special characters are: !@#$%^&*()-+

"ADG787gbujI^%^%T&g" will output True
"AGjy%^&gtf" will output False

**Comment by BhargaviChada** [comment]
Can I take this in Java?

**Comment by EANimesha** [comment]
I can do this in python

**Comment by Aashrut** [comment]
Hey @aditya109 , I have made this program in python. Can you check it out.

**Comment by aditya109** [comment]
Hey @Aashrut ! Would you mind linking your PR to this issue ?

**Comment by aditya109** [comment]
> I can do this in python

Hi @EANimesha, I am sorry I can't assign this issue has already been claimed, but feel free to raise one and link this issue. I will approve your PR and tag it `hacktoberfest-accepted` which carries the same value and will counted in Hacktoberfest stats. Also a humble request could please star the repo, it helps in encouraging contributions.

**Comment by Aashrut** [comment]
hey, @aditya109 , I have linked this issue to my PR.

**Comment by aditya109** [comment]
> hey, @aditya109 , I have linked this issue to my PR.

Yes it is merged.

**Comment by Aashrut** [comment]
😁.Actually, I am just a newbie in making PR and issues.😅
