### ISSUE TITLE
Create a Program that checks if the given password is strong or not. | Java

### ISSUE THREAD

**Issue by aditya109** [aditya109/git-osp-for-beginners#126]
If the password is strong then it should return True and if the password is not strong enough then it should return False.
Here are the conditions for the password to be strong:

Its length is at least 8.
It contains at least one digit.
It contains at least one lowercase English character.
It contains at least one uppercase English character.
It contains at least one special character. The special characters are: !@#$%^&*()-+
"ADG787gbujI^%^%T&g" will output True
"AGjy%^&gtf" will output False

**Comment by EANimesha** [comment]
I can solve this problem. Assign me

**Comment by asunawesker** [comment]
Hi @aditya109 could you assign this to me?

**Comment by IshaanSinghal1** [comment]
Assign this to me

**Comment by ridhikapila27** [comment]
Kindly assign me this issue

**Comment by aditya109** [comment]
Hi @IshaanSinghal1 @EANimesha @asunawesker @ridhikapila27 ! Sure please go ahead and resolve this issue. I will assign this issue to you guys. A humble request to star this repo to encourage further contributions.

**Comment by arpita2712** [comment]
Hey, may I solve this ?
