### ISSUE TITLE
Create a Program that checks if the given password is strong or not. | C++

### ISSUE THREAD

**Issue by aditya109** [aditya109/git-osp-for-beginners#127]
If the password is strong then it should return True and if the password is not strong enough then it should return False.
Here are the conditions for the password to be strong:

Its length is at least 8.
It contains at least one digit.
It contains at least one lowercase English character.
It contains at least one uppercase English character.
It contains at least one special character. The special characters are: !@#$%^&*()-+
"ADG787gbujI^%^%T&g" will output True
"AGjy%^&gtf" will output False

**Comment by Aryan-dev007** [comment]
I would love to contribute to this project!
Please assign it to me

**Comment by Aryan-dev007** [comment]
#130
