### ISSUE TITLE
Create the Program to find the Factorial of a Number | Python

### ISSUE THREAD

**Issue by EANimesha** [aditya109/git-osp-for-beginners#128]
Create a function that receives a non-negative integer and returns the factorial of that number.

Examples:

- fact(0) ➞ 1
- fact(1) ➞ 1
- fact(3) ➞ 3 * 2 * 1 = 6
- fact(6) ➞ 6 * 5 * 4 * 3 * 2 * 1 = 720

**Comment by EANimesha** [comment]
I like to do this. Assign me

**Comment by TineoC** [comment]
#134

**Comment by TineoC** [comment]
#134

**Comment by EANimesha** [comment]
Sorry. duplication found
