### ISSUE TITLE
Roots of Quadratic Equation | Python

### ISSUE THREAD

**Issue by vijay5158** [aditya109/git-osp-for-beginners#131]
Program - which takes inputs of the coefficients of a Quadratic Equation and outputs roots of the equation.
For ex- the format of quadratic eq is ' a*x^2 + b*x + c '
Program takes input the value of a,  b, c and gives out roots the eq.

**Comment by chatRG** [comment]
I can try this!

**Comment by shubhamnag14** [comment]
can i solve this issue..please assign me this issue

**Comment by avishekchoudhary** [comment]
Please assign it to me.

**Comment by TohDeKai** [comment]
Please assign me the issue, I'm interested to work on it. Thank you
