### ISSUE TITLE
Bug in DisplayPrimeArrayElements.java 

### ISSUE THREAD

**Issue by bhaskarsantoshk** [aditya109/git-osp-for-beginners#147]
**Describe the bug**
Input is always 0 - (int) Math.random()

**To Reproduce**
Self explanatory

**Expected behavior**
Input should be given by user or proper random generation

**Additional context**
Modularisation and Readability

**Comment by aditya109** [comment]
Hi @aditya109 ! Mind if I ask why did you assign this issue to me ?? 😁

**Comment by bhaskarsantoshk** [comment]
@aditya109 sorry , it looks like you are default assignee. Please assign it to me , I am raising the pr.

**Comment by bhaskarsantoshk** [comment]
@aditya109 here is the PR: https://github.com/aditya109/git-osp-for-beginners/pull/149
