### ISSUE TITLE
Refactor Required URGENT !!

### ISSUE THREAD

**Issue by aditya109** [aditya109/git-osp-for-beginners#155]
The Repository has become a mess. Would any of the brave souls like the responsibility of cleaning the repository up? 
The PR merge will be halted until this issue is closed.
Tasks to be done :

- [ ] The `Programming` directory must contain the following directories:
  - [ ] Java
  - [ ] Python
  - [ ] C++
  - [ ] C
  - [ ] C#
  - [ ] Javascript
  - [ ] Golang
- [ ] The `languages` directory should sub-directories, each containing only 1 program file
  - [ ] Each sub-directory must be renamed to name **CamelCased** name of the File
  - [ ] No file must be left with out a folder.
- [ ] Outside `Programming` directory there must not remain any file except:
  1. `.gitignore`
  2. `LICENSE.txt`
  3. `README.md`
  4. `contribution_guidelines.md`
  5. `github_cmd.md`
  6. `open_source.md`
- [ ] Apart from this, if there are any other forms of restructuring are welcome.

**Comment by xloli20** [comment]
Hello, I can work on this issue!

**Comment by aditya109** [comment]
Hi @xloli20 ! You're are a life saver! Thanks for the rescue. I will assign this to you.

**Comment by xloli20** [comment]
no problem 👍

**Comment by bhaskarsantoshk** [comment]
@aditya109 Could you assign me?
