### ISSUE TITLE
Display Highest Runs Scored (Java)

### ISSUE THREAD

**Issue by aditya109** [aditya109/git-osp-for-beginners#19]
Write a Program to store runs scored by 11 cricketers of Premier League along with their names. Now display the name of highest scoring cricketer who has made the highest score along with runs.

**Comment by aryankr2005** [comment]
Hello @aditya109 I am a keen programmer who would like to work on this issue. This is my first time exploring GitHub and open source repositories. Can I work on the java portion?

**Comment by aditya109** [comment]
Sure @aryankr2005 Why not? Please go ahead. I see you have just started on Git. Have fun #hacking.

**Comment by aryankr2005** [comment]
Thank you.
