### ISSUE TITLE
Creation of a Discord Server

### ISSUE THREAD

**Issue by aditya109** [aditya109/git-osp-for-beginners#204]
To increase inter-contributor communication, would guys would a `Discord` server ?

Please share your views regarding this matter.

**Comment by hryxna** [comment]
Well having our own Discord server is a good idea @aditya109 

But I'm not that much into discord and frankly speaking there might be times when people just would spam for PR and other things 😅.

If you find anyone who's ready to maintain a discord server then I'll gladly help you 😄.

Even I'm not sure about myself maintaining a discord as I'm already finding a job for myself
If I find one then I would be barely touching discord 😅.

**Comment by aditya109** [comment]
> Well having our own Discord server is a good idea @aditya109
> 
> But I'm not that much into discord and frankly speaking there might be times when people just would spam for PR and other things 😅.
> 
> If you find anyone who's ready to maintain a discord server then I'll gladly help you 😄.
> 
> Even I'm not sure about myself maintaining a discord as I'm already finding a job for myself
> If I find one then I would be barely touching discord 😅.

I think so too. But there will folks who wanted to start some sort of discussion board. I wasn't really sure about it myself, so I opened the issue. 
I wasn't really asking you to manage a Discord server 😅. I was just perusing along the lines. Anyways, all the best on your job hunt. 
If it wouldn't be too much trouble @hryxna , could I ask if we could communicate over mail ?

**Comment by hryxna** [comment]
> > Well having our own Discord server is a good idea @aditya109
> > 
> > But I'm not that much into discord and frankly speaking there might be times when people just would spam for PR and other things 😅.
> > 
> > If you find anyone who's ready to maintain a discord server then I'll gladly help you 😄.
> > 
> > Even I'm not sure about myself maintaining a discord as I'm already finding a job for myself
> > If I find one then I would be barely touching discord 😅.
> 
> I think so too. But there will folks who wanted to start some sort of discussion board. I wasn't really sure about it myself, so I opened the issue. 
> I wasn't really asking you to manage a Discord server 😅. I was just perusing along the lines. Anyways, all the best on your job hunt. 
> If it wouldn't be too much trouble @hryxna , could I ask if we could communicate over mail ?  

I totally get your point about discord 👍🏻.
Sure you can reach out to me over mail
hk20726@gmail.com

**Comment by hryxna** [comment]
Thanks btw @aditya109 😀
Let's see what job is waiting for me 😂

**Comment by aditya109** [comment]
> Thanks btw @aditya109 😀
> Let's see what job is waiting for me 😂

Thanks hope you find it soon ! 😋

**Comment by aditya109** [comment]
Am closing this issue. 😁

**Comment by hryxna** [comment]
Cool 👍🏻
