### ISSUE TITLE
Add Two Numbers

### ISSUE THREAD

**Issue by aditya109** [aditya109/git-osp-for-beginners#205]
Add Two Numbers
----------------------------------------------------------
You are given two non-empty linked lists representing two non-negative integers. The digits are stored in reverse order, and each of their nodes contains a single digit. Add the two numbers and return the sum as a linked list.

You may assume the two numbers do not contain any leading zero, except the number 0 itself.

----------------------------------------------------------
**Example 1:**

Input: l1 = [2,4,3], l2 = [5,6,4]
Output: [7,0,8]
Explanation: 342 + 465 = 807.

**Example 2:**

Input: l1 = [0], l2 = [0]
Output: [0]

**Example 3:**

Input: l1 = [9,9,9,9,9,9,9], l2 = [9,9,9,9]
Output: [8,9,9,9,0,0,0,1]

----------------------------------------------------------
### Constraints:

The number of nodes in each linked list is in the range [1, 100].
0 <= Node.val <= 9
It is guaranteed that the list represents a number that does not have leading zeros.

**Comment by Hitesh77** [comment]
Hi @aditya109,

I would like to work on this, can you please me the same?

Thanks

**Comment by asheemchhetri** [comment]
Making an attempt on this issue.

**Comment by aditya109** [comment]
Hi @Hitesh77 @asheemchhetri ! Please go ahead and work on this issue. I am assigning this to both of you. Just link this issue in your respective PR.

**Comment by asheemchhetri** [comment]
PR opened for python Solution with testcases: https://github.com/aditya109/git-osp-for-beginners/pull/225

**Comment by asheemchhetri** [comment]
PR updated! #225
