### ISSUE TITLE
Reverse Integer

### ISSUE THREAD

**Issue by aditya109** [aditya109/git-osp-for-beginners#206]
Reverse Integer
----------------------------------------------------------------
Given a 32-bit signed integer, reverse digits of an integer.

**Note:**
Assume we are dealing with an environment that could only store integers within the 32-bit signed integer range: [−231,  231 − 1]. For the purpose of this problem, assume that your function returns 0 when the reversed integer overflows.

------------------------------------------------------------------

**Example 1:**

Input: x = 123
Output: 321

**Example 2:**

Input: x = -123
Output: -321

**Example 3:**

Input: x = 120
Output: 21

**Example 4:**

Input: x = 0
Output: 0

------------------------------------------------------------------ 

### Constraints:

`-231 <= x <= 231 - 1`

**Comment by CodeAught** [comment]
I wanna work on it, assign it to me please.

**Comment by RishavHimmatramka** [comment]
I know the program in python. Pls assign me.

**Comment by aditya109** [comment]
Hi @CodeAught @RishavHimmatramka ! Please go ahead and work on this issue. I am assigning this to both of you. Just link this issue in your respective PR.

**Comment by damiansikora85** [comment]
I will work with C#

**Comment by Suraj1199** [comment]
I can do the program in C, C++, Java, Python , which ever language is left pls assign it to me.

**Comment by 96RadhikaJadhav** [comment]
I would like to work on the issue..will write a python program..Could you please assign it to me?

**Comment by ghanender-chauhan** [comment]
Assign this to me i will do in python

**Comment by aditya109** [comment]
Hi @damiansikora85 @Suraj1199 @96RadhikaJadhav @ghanender-chauhan Please go on ahead and raise a PR for the same, linking this issue. I am assigning this issue to you guys as well. Please consider starring the repo, if you have not already to encourage further contributions.

**Comment by pardeep596** [comment]
I can make this program in java and c++ please assign it to me
