### ISSUE TITLE
Longest Substring Without Repeating Characters

### ISSUE THREAD

**Issue by aditya109** [aditya109/git-osp-for-beginners#207]
Given a string s, find the length of the longest substring without repeating characters.

------------------------------------------------------ 

**Example 1:**

Input: s = "abcabcbb"
Output: 3
Explanation: The answer is "abc", with the length of 3.

**Example 2:**

Input: s = "bbbbb"
Output: 1
Explanation: The answer is "b", with the length of 1.

**Example 3:**

Input: s = "pwwkew"
Output: 3
Explanation: The answer is "wke", with the length of 3.
Notice that the answer must be a substring, "pwke" is a subsequence and not a substring.

**Example 4:**

Input: s = ""
Output: 0
 
---------------------------------------------------------

### Constraints:

0 <= s.length <= 5 * 104
s consists of English letters, digits, symbols and spaces.

**Comment by nikhil05-code** [comment]
Please assign it to me. I would like to work on it.

**Comment by aditya109** [comment]
Hi @nikhil05-code ! Please go on ahead and raise a PR for the same, linking this issue. Please consider starring the repo, if you have not already to encourage further contributions.

**Comment by demonslayer99** [comment]
assign me this for c#
