### ISSUE TITLE
Median of Two Sorted Arrays

### ISSUE THREAD

**Issue by aditya109** [aditya109/git-osp-for-beginners#208]
Median of Two Sorted Arrays
------------------------------------------------

Given two sorted arrays **nums1** and **nums2** of size **m** and **n** respectively, return the **median** of the two sorted arrays.

Follow up: The overall run time complexity should be `O(log (m+n))`.

------------------------------------------------------
**Example 1:**

Input: nums1 = [1,3], nums2 = [2]
Output: 2.00000
Explanation: merged array = [1,2,3] and median is 2.

**Example 2:**

Input: nums1 = [1,2], nums2 = [3,4]
Output: 2.50000
Explanation: merged array = [1,2,3,4] and median is (2 + 3) / 2 = 2.5.

**Example 3:**

Input: nums1 = [0,0], nums2 = [0,0]
Output: 0.00000

**Example 4:**

Input: nums1 = [], nums2 = [1]
Output: 1.00000

**Example 5:**

Input: nums1 = [2], nums2 = []
Output: 2.00000
 
-------------------------------------------------------------------

**Constraints:**

`nums1.length == m`
`nums2.length == n`
`0 <= m <= 1000`
`0 <= n <= 1000`
`1 <= m + n <= 2000`
`-106 <= nums1[i], nums2[i] <= 106`

**Comment by Hitesh77** [comment]
Hi @aditya109,

I would like to work on this in java, can you please assign me this task?

Thanks

**Comment by leli-1** [comment]
Can you assign this to me for python language?

**Comment by shree-create** [comment]
I want to work on this in C,can you assign this task to me?

**Comment by aditya109** [comment]
Hi @Hitesh77 @shree-create @leli-1 ! Please go on ahead and raise a PR for the same, linking this issue. Please consider starring the repo, if you have not already to encourage further contributions.

**Comment by demonslayer99** [comment]
assign it to me for c#

**Comment by hryxna** [comment]
@aditya109  I'll be doing it in JAVA.
Please assign this to me as well 😄.

**Comment by Hitesh77** [comment]
Hi @hryxna,

I am already working on this.
Can you please check out other issues on the list?

Thanks

**Comment by hryxna** [comment]
> Hi @hryxna,
> 
> I am already working on this.
> Can you please check out other issues on the list?
> 
> Thanks

Don't worry i won't raise a PR until and unless you do 
Also i have already completed the program 😀.
If there's any doubt then go ahead and ask me.

**Comment by ghanender-chauhan** [comment]
hi Assign this to me I will do in python
