### ISSUE TITLE
Longest Palindromic Substring

### ISSUE THREAD

**Issue by aditya109** [aditya109/git-osp-for-beginners#209]
Longest Palindromic Substring
------------------------------------------------
Given a string s, return the longest palindromic substring in s.

**Example 1:**

Input: s = "babad"
Output: "bab"
Note: "aba" is also a valid answer.

**Example 2:**

Input: s = "cbbd"
Output: "bb"

**Example 3:**

Input: s = "a"
Output: "a"

**Example 4:**

Input: s = "ac"
Output: "a"
 
------------------------------------------------------------

### Constraints:

`1 <= s.length <= 1000`
**s** consist of only digits and English letters (lower-case and/or upper-case),

**Comment by rarchitgupta** [comment]
Can you assign this to me for C++

**Comment by leli-1** [comment]
Can you assign this to me for python language?

**Comment by aditya109** [comment]
Hi @rarchitgupta @leli-1 ! Please go on ahead and raise a PR for the same, linking this issue. I am assigning this issue to you guys. Please consider starring the repo, if you have not already to encourage further contributions.

**Comment by harshitashankar** [comment]
Please assign to me for java.

**Comment by Suraj1199** [comment]
I can do in C++, C, Java, Python. Which ever is left pls assign it to me in that language.

**Comment by aditya109** [comment]
Hi @harshitashankar @Suraj1199 ! Please go on ahead and raise a PR for the same, linking this issue. I am assigning this issue to you guys as well. Please consider starring the repo, if you have not already to encourage further contributions.

**Comment by natzoz** [comment]
Hello @aditya109 may I be assigned to this if it is still open? I hope to try it using Java.
