### ISSUE TITLE
Count The Words Starting With Vowels (Java)

### ISSUE THREAD

**Issue by aditya109** [aditya109/git-osp-for-beginners#21]
Write a Program to input a sentence and count and print the number of words starting with a vowel.

**Comment by aryankr2005** [comment]
Hello @aditya109 I am a keen programmer who would like to work on this issue. This is my first time exploring GitHub and open source repositories. Can I work on the java portion?

**Comment by aditya109** [comment]
Hi @aryankr2005. Ok then I have assigned this issue to you. Have fun #hacking!
