### ISSUE TITLE
ZigZag Conversion

### ISSUE THREAD

**Issue by aditya109** [aditya109/git-osp-for-beginners#210]
ZigZag Conversion
----------------------------------------------------
The string `"PAYPALISHIRING"` is written in a zigzag pattern on a given number of rows like this: (you may want to display this pattern in a fixed font for better legibility)
```
P   A   H   N
A P L S I I G
Y   I   R
```
And then read line by line: `"PAHNAPLSIIGYIR"`

Write the code that will take a string and make this conversion given a number of rows:
```
string convert(string s, int numRows);
``` 
------------------------------------------------
**Example 1:**
```
Input: s = "PAYPALISHIRING", numRows = 3
Output: "PAHNAPLSIIGYIR"
```
**Example 2:**
```
Input: s = "PAYPALISHIRING", numRows = 4
Output: "PINALSIGYAHRPI"
Explanation:
P     I    N
A   L S  I G
Y A   H R
P     I
```
**Example 3:**
```
Input: s = "A", numRows = 1
Output: "A"
```
------------------------------------------------
### Constraints:

`1 <= s.length <= 1000`
**s** consists of English letters (lower-case and upper-case), ',' and '.'.
`1 <= numRows <= 1000`

**Comment by I3han** [comment]
Can I work on this

**Comment by I3han** [comment]
@aditya109 can you check the PR, Thank you

**Comment by aditya109** [comment]
Hi @I3han ! Please go on ahead and raise a PR for the same, linking this issue. I am assigning this issue to you. Please consider starring the repo, if you have not already to encourage further contributions.

**Comment by I3han** [comment]
@aditya109 I have raise a PR #215

**Comment by natzoz** [comment]
Hello @aditya109, may I try this using Java?
