### ISSUE TITLE
Count The Words Starting With Vowels (C++)

### ISSUE THREAD

**Issue by aditya109** [aditya109/git-osp-for-beginners#23]
Write a Program to input a sentence and count and print the number of words starting with a vowel.

**Comment by dibakar95** [comment]
@aditya109 I would like to take this issue.

**Comment by aditya109** [comment]
Hi @dibakar95 ! Sure please go ahead and resolve this issue. I will assign this issue to you. A humble request to star this repo to encourage further contributions.

**Comment by sakshi-negi123** [comment]
please assign this to me. I have the solution ready

**Comment by NidhiNivedita6** [comment]
Please assign me this.

**Comment by kokum007** [comment]
i would like to do a vowel search programme in c sharp assign it for me?

**Comment by aditya109** [comment]
> Please assign me this.

Hi @NidhiNivedita6 !  ! Sure please go ahead and resolve this issue. I will assign this issue to you. A humble request to star this repo to encourage further contributions.
