### ISSUE TITLE
Regular Expression Matching

### ISSUE THREAD

**Issue by aditya109** [aditya109/git-osp-for-beginners#231]
Regular Expression Matching
---------------------------------------------------
Given an input string (s) and a pattern (p), implement regular expression matching with support for '.' and '*' where: 

'.' Matches any single character.​​​​
'*' Matches zero or more of the preceding element.
The matching should cover the entire input string (not partial).

---------------------------------------------------
**Example 1:**

Input: s = "aa", p = "a"
Output: false
Explanation: "a" does not match the entire string "aa".

**Example 2:**

Input: s = "aa", p = "a*"
Output: true
Explanation: '*' means zero or more of the preceding element, 'a'. Therefore, by repeating 'a' once, it becomes "aa".

**Example 3:**

Input: s = "ab", p = ".*"
Output: true
Explanation: ".*" means "zero or more (*) of any character (.)".

**Example 4:**

Input: s = "aab", p = "c*a*b"
Output: true
Explanation: c can be repeated 0 times, a can be repeated 1 time. Therefore, it matches "aab".

**Example 5:**

Input: s = "mississippi", p = "mis*is*p*."
Output: false

---------------------------------------------------
### Constraints:

`0 <= s.length <= 20`
`0 <= p.length <= 30`
s contains only lowercase English letters.
p contains only lowercase English letters, '.', and '*'.

**Comment by hryxna** [comment]
If I were to implement it in java it would be a couple of lines of code 😁. @aditya109

**Comment by asadkhalid305** [comment]
Can I submit this in JavaScript?

**Comment by aditya109** [comment]
> If I were to implement it in java it would be a couple of lines of code 😁. @aditya109

I agree. I think we should leave issues like for VSC Freshers. 😁

**Comment by aditya109** [comment]
Hi @asadkhalid305 ! 
Please go on ahead and raise a PR for the same, linking this issue. I am assigning this issue to you guys. Please consider starring the repo, if you have not already to encourage further contributions.

**Comment by SaxenaKartik** [comment]
Shall I contribute in a working code in Python3?

**Comment by hryxna** [comment]
sure @SaxenaKartik go ahead 😄.

**Comment by SaxenaKartik** [comment]
Could you please add me to the assignees?
It feels ethical to work on an assigned issue 
I will be sending forth a PR asap

**Comment by SaxenaKartik** [comment]
I have written the code for the problem 
I had one small concern though, based on the example outputs 

**Example 3** must have the given input pattern as `p = .*` 
**Example 4** must have the given input pattern as `p = c*a*b` OR `p = c*a.b` 

If I am misunderstanding anything please let me know

**Comment by hryxna** [comment]
> I have written the code for the problem
> I had one small concern though, based on the problem description and example outputs
> 
> **Example 3** must have the given input pattern as `p = .*`
> **Example 4** must have the given input pattern as `p = c*a*b` OR `p = c*a.b`
> 
> If I am misunderstanding anything please let me know

@SaxenaKartik 
- As per your concern, I agree that the input pattern must be in the way you have shown for both  **Example 3** & **Example 4**
- Because it would be Zero or more time for ("*"), (".") means any character
   and one or more times for ("+").

**Comment by SaxenaKartik** [comment]
Yes exactly 
Thank you for clarifying it @hryxna 
Could you assign me the issue for me to make a PR?

**Comment by hryxna** [comment]
Sorry, I'm not the person who assigns contributors @SaxenaKartik 😅.
But I would advise you to raise and wait for the @aditya109 to review it.
Don't worry I'm aware that you have already mentioned this earlier, But wait and have patience 😄 
and make your PR addressing the Issue.

**Comment by SaxenaKartik** [comment]
Hey! @hryxna @aditya109 
Could someone review my PR #266 ?

**Comment by hryxna** [comment]
> Hey! @hryxna @aditya109
> Could someone review my PR #266?

Done check out the review 😄 @SaxenaKartik
