### ISSUE TITLE
Container With Most Water

### ISSUE THREAD

**Issue by aditya109** [aditya109/git-osp-for-beginners#232]
Container With Most Water
------------------------------------------------
Given n non-negative integers a1, a2, ..., an , where each represents a point at coordinate (i, ai). n vertical lines are drawn such that the two endpoints of the line i is at (i, ai) and (i, 0). Find two lines, which, together with the x-axis forms a container, such that the container contains the most water.

Notice that you may not slant the container.

------------------------------------------------
**Example 1:**

![question_11](https://user-images.githubusercontent.com/22005947/96469675-1dfe8a00-124b-11eb-9593-4bca4c786864.jpg)

Input: height = [1,8,6,2,5,4,8,3,7]
Output: 49
Explanation: The above vertical lines are represented by array [1,8,6,2,5,4,8,3,7]. In this case, the max area of water (blue section) the container can contain is 49.

**Example 2:**

Input: height = [1,1]
Output: 1

**Example 3:**

Input: height = [4,3,2,1,4]
Output: 16

**Example 4:**

Input: height = [1,2,1]
Output: 2

------------------------------------------------
### Constraints:

`2 <= height.length <= 3 * 104`
`0 <= height[i] <= 3 * 104`

**Comment by drstrange11** [comment]
I would like to work on this issue

**Comment by aditya109** [comment]
Hi @drstrange11 ! Please go on ahead and raise a PR for the same, linking this issue. I am assigning this issue to you guys. Please consider starring the repo, if you have not already to encourage further contributions.

**Comment by vat0599** [comment]
Hi @aditya109 can you assign this to me?
I would like to implement using Python
Thanks

**Comment by aditya109** [comment]
Hi @drstrange11 @vat0599 ! Please go on ahead and raise a PR for the same, linking this issue. I am assigning this issue to you guys. Please consider starring the repo, if you have not already to encourage further contributions.

**Comment by vat0599** [comment]
@aditya109 , the python soln already exists in ur repo
@drstrange11 already gave a solution
I think you can close this issue
