### ISSUE TITLE
Additon of digits of a given number  

### ISSUE THREAD

**Issue by PardeepKumar816** [aditya109/git-osp-for-beginners#235]
Example :
input = 254
output = 11

**Comment by pardeep596** [comment]
can i make this program in java and c++

**Comment by yoki-07** [comment]
I want to contribute in this by providing code in C language @pardeep596 . Please assign me this.

**Comment by asadkhalid305** [comment]
I can make this program in any language. Let me know and assign.

**Comment by aditya109** [comment]
Hi @asadkhalid305 @pardeep596 @yoki-07 ! Sure.
Please go on ahead and raise a PR for the same, linking this issue. I am assigning this issue to you guys. Please consider starring the repo, if you have not already to encourage further contributions.

**Comment by ravenblack24** [comment]
I'll take JavaScript please

**Comment by pardeep596** [comment]
I have made this program in java 
pull request #250

**Comment by alexkimeu0** [comment]
I would like to take this using JavaScript.

**Comment by ShantiMow** [comment]
Can I solve it in java?

**Comment by cyenney** [comment]
Can you assign to me in C#?

**Comment by MaathavanJkr** [comment]
I have made python solution. #255

**Comment by PulsaraSandeepa** [comment]
Can I work on this in Java?

**Comment by aniket173000** [comment]
HI can u please assign this issue to me . I can do it using C,C++,python,JAVA.

**Comment by asadkhalid305** [comment]
Hey!! can you please review and merge my [PR](https://github.com/aditya109/git-osp-for-beginners/pull/256)

**Comment by shashan27** [comment]
Hi..
Could u assign me this program, I can deliver it in any language.

**Comment by ghanender-chauhan** [comment]
hii @PardeepKumar816  please assign me this i will do in python
