### ISSUE TITLE
Count The Words Starting With Vowels (Python)

### ISSUE THREAD

**Issue by aditya109** [aditya109/git-osp-for-beginners#24]
Write a Program to input a sentence and count and print the number of words starting with a vowel.

**Comment by mansiwagh05** [comment]
Hi, I would like to work on this

**Comment by aditya109** [comment]
Hi @mansiwagh05 ! Sure please go ahead and resolve this issue. I will assign this issue to you. A humble request to star this repo to encourage further contributions.

**Comment by alsam123** [comment]
Hey, @aditya109 I am interested in doing it...could you please assign it to me?
