### ISSUE TITLE
[Question] Rotate array Left K times and Right K times.

### ISSUE THREAD

**Issue by hrj-star** [aditya109/git-osp-for-beginners#243]
**Problem : Given an array , return its left rotated and right rotated array by K positions.**

Sample Input : arr [] =1 2 3 4 5 ,   K = 5

Output : 
Left Rotated array by K=5 times : 1 2 3 4 5
Right Rotated array by K =5 times : 1 2 3 4 5

Sample Input : arr [] =1 2 3 4 5 ,   K = 4

Left Rotated array by K=4 times : 5 1 2 3 4
Right Rotated array by K =4 times : 2 3 4 5 1

Will implement in Java.

**Comment by pranatimittal** [comment]
Can you assign it to me for Java?

**Comment by prinsusinghal** [comment]
Can you assign it to me for C++?

**Comment by Ajordat** [comment]
Are you sure that's the expected output in that case? To me it looks like it would remain the same in that case, since k equals the length of the array.

Input:
array = [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
k = 4

Output:
Left-rotated array K(4) times: [4, 5, 6, 7, 8, 9, 0, 1, 2, 3]
Right-rotated array K(4) times: [6, 7, 8, 9, 0, 1, 2, 3, 4, 5]

I will do this in Python.

**Comment by hrj-star** [comment]
> Are you sure that's the expected output in that case? To me it looks like it would remain the same in that case, since k equals the length of the array.
> 
> Input:
> array = [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
> k = 4
> 
> Output:
> Left-rotated array K(4) times: [4, 5, 6, 7, 8, 9, 0, 1, 2, 3]
> Right-rotated array K(4) times: [6, 7, 8, 9, 0, 1, 2, 3, 4, 5]
> 
> I will do this in Python.

Yes , there was a typo mistake , the output was for  K=4 , have updated , many thanks !

**Comment by prinsusinghal** [comment]
Please review my PR: rotate array left k times and right k times. #243 SOLUTION C++ #249

**Comment by Ajordat** [comment]
Added PR #257 to solve this in Python.

**Comment by pranatimittal** [comment]
Please check PR: #251 for Java Solution

**Comment by hrj-star** [comment]
@aditya109  Dont we have to have to work on PRs after  you assign us the issue ?

**Comment by aditya109** [comment]
Hi @pranatimittal @prinsusinghal @Ajordat @hrj-star @cyenney ! Great work on your PR ! If you have not please consider starring this repo to encourage further contributions.

**Comment by aditya109** [comment]
> @aditya109 Dont we have to have to work on PRs after you assign us the issue ?

Hi @hrj-star ! No it is not really compulsory. Please raise a PR whenever you see fit.

**Comment by pranatimittal** [comment]
Thank you @aditya109. Will you please Merge the PR or add hacktoberfest-accepted lable?  It will then be counted as one of my PR

**Comment by prinsusinghal** [comment]
> Please review my PR: rotate array left k times and right k times. #243 SOLUTION C++ #249

Yes @aditya109 do the same with my PR also
