### ISSUE TITLE
Count The Words Starting With Vowels (Golang)

### ISSUE THREAD

**Issue by aditya109** [aditya109/git-osp-for-beginners#25]
Write a Program to input a sentence and count and print the number of words starting with a vowel.

**Comment by alsam123** [comment]
Hey, @aditya109 I am interested in doing it...could you please assign it to me?

**Comment by gaurangisinha** [comment]
> Write a Program to input a sentence and count and print the number of words starting with a vowel.

Hello, @aditya109 I am very keen on solving it, could you please assign it to me. I would be extremely grateful.

**Comment by Rishabrp99** [comment]
hey @aditya109 this is rishab  can you please assign it to me ??  I would love to solve the problem and would be very grateful for the same.

**Comment by riyagoel192** [comment]
Do we have to submit the solution in Java language?

**Comment by vrinda41198** [comment]
Hello, Can I also please give this a try?

**Comment by arnauvila33** [comment]
Hello @aditya109 I'm interested in trying it! Could you assign it to me, please?

**Comment by aditya109** [comment]
Hi @vrinda41198 @arnauvila33 ! Sure please go ahead and resolve this issue. I will assign this issue to you. A humble request to star this repo to encourage further contributions.

**Comment by aditya109** [comment]
> Do we have to submit the solution in Java language?

Hi @riyagoel192 ! It completely depends on you. Do it in whatever language you wish to choose. Just link the relative issue and raise a PR.
