### ISSUE TITLE
Display Highest Runs Scored (C++)

### ISSUE THREAD

**Issue by aditya109** [aditya109/git-osp-for-beginners#26]
Write a Program to store runs scored by 11 cricketers of Premier League along with their names. Now display the name of highest scoring cricketer who has made the highest score along with runs.

**Comment by sakshi-negi123** [comment]
please assign it to me

**Comment by aditya109** [comment]
Hi @sakshi-negi123 ! Sure please go ahead and resolve this issue. I will assign this issue to you. A humble request to star this repo to encourage further contributions.

**Comment by mohitrathor98** [comment]
Hi! Please assign it to me

**Comment by aditya109** [comment]
> Hi! Please assign it to me

Hi @mohitrathor98 I have assigned this to you as well. A humble request to star this repo to encourage further contributions.

**Comment by mohitrathor98** [comment]
Sure

**Comment by Rahul171201** [comment]
pls assign it to me...I am new to github and searching for such repos to start !!

**Comment by gaurangisinha** [comment]
> Write a Program to store runs scored by 11 cricketers of Premier League along with their names. Now display the name of highest scoring cricketer who has made the highest score along with runs.

Hello, @aditya109  could you please assign this to me? I would be grateful.

**Comment by aditya109** [comment]
Hi @Rahul171201 @gaurangisinha ! The thing is I can't this issue has already been claimed or merge your PR, but feel free to raise one and link this issue. I will approve your PR and tag it `hacktoberfest-accepted` which carries the same value and will counted in Hacktoberfest stats. Also a humble request could please star the repo, it helps in encouraging contributions.

**Comment by Rahul171201** [comment]
@aditya109 Thankyou for the recognition. I have done as said by you.

**Comment by kajalrawal** [comment]
please assign this to me @aditya109
