### ISSUE TITLE
To create a Zoo with animals

### ISSUE THREAD

**Issue by Mandroid-42** [aditya109/git-osp-for-beginners#267]
I want to creat a zoo where you can add animals, the zoo have some method that then wold be tested in a testdriver. Want to do this in Java.

**Comment by Yasas4D** [comment]
Hi, I would like to work on this.. Can you assign me, please

**Comment by Yasas4D** [comment]
Hi I created the application.. 
![screenshot_17](https://user-images.githubusercontent.com/49401137/97083865-cd16d900-1630-11eb-83d0-362f3fdccaec.png)
![screenshot_18](https://user-images.githubusercontent.com/49401137/97083867-cf793300-1630-11eb-9051-ac75901f7ede.png)


This is the video demo of it.. Please accept the pull request and accept as a hacktomber answer.. Thank you
[zoo-.zip](https://github.com/aditya109/git-osp-for-beginners/files/5432992/zoo-.zip)

**Comment by aditya109** [comment]
Hi @Yasas4D @Mandroid-42 ! Please go on ahead and raise a PR for the same, linking this issue. I am assigning this issue to you guys. Please consider starring the repo, if you have not already to encourage further contributions.
