### ISSUE TITLE
Display Highest Runs Scored (Python)

### ISSUE THREAD

**Issue by aditya109** [aditya109/git-osp-for-beginners#27]
Write a Program to store runs scored by 11 cricketers of Premier League along with their names. Now display the name of highest scoring cricketer who has made the highest score along with runs.

**Comment by mansiwagh05** [comment]
Hi, I would like to work on this

**Comment by gaurangisinha** [comment]
Hello, @aditya109 I am very keen on solving it, could you please assign it to me. I would be grateful.

**Comment by DiveshHariani** [comment]
Hi @aditya109, Can you please assign this task to me?

**Comment by aditya109** [comment]
> Hi, I would like to work on this

Hi @mansiwagh05, I will assign this issue to you.

**Comment by aditya109** [comment]
> Hello, @aditya109 I am very keen on solving it, could you please assign it to me. I would be grateful.

@gaurangisinha I am sorry I can't this issue has already been claimed or merge your PR, but feel free to raise one and link this issue. I will approve your PR and tag it `hacktoberfest-accepted` which carries the same value and will counted in Hacktoberfest stats. Also a humble request could please star the repo, it helps in encouraging contributions.

**Comment by aditya109** [comment]
> Hi @aditya109, Can you please assign this task to me?

Hi @DiveshHariani, I am sorry I can't this issue has already been claimed or merge your PR, but feel free to raise one and link this issue. I will approve your PR and tag it `hacktoberfest-accepted` which carries the same value and will counted in Hacktoberfest stats. Also a humble request could please star the repo, it helps in encouraging contributions.
