### ISSUE TITLE
Class names need to be modified, In java programs file names and class names are different. 

### ISSUE THREAD

**Issue by yjoshi** [aditya109/git-osp-for-beginners#271]
For example in 

- In TemperatureConversion  Folder: celciusToFarenheit file,class name was temperature!

- In CheckPrime folder file name is checkPrime but class name is CheckPrime,

- In PalindromeOrNot file class name is Palindrome!

many more....

- Naming convention needs to be followed.

**Comment by yjoshi** [comment]
I have Resolved this in the recent PR #273

**Comment by aditya109** [comment]
Hi @yjoshi ! Thanks for opening this issue. Since the issue is resolved by your PR, I'd close close it for now. Happy Hacking!
