### ISSUE TITLE
Roman_to_Integer

### ISSUE THREAD

**Issue by harshbhagwani94** [aditya109/git-osp-for-beginners#275]
Converting Roman Numerals to Integer. 
We know Roman numerals are represented by seven different symbols: I, V, X, L, C, D and M.
Symbol       Value
I                  1
V                5
X                10
L                50
C               100
D               500
M              1000

Example:
1. Input     : III
   Output  : 3
2. Input     : IX
   Output  : 9
3. Input     : MCMXCIV
   Output  : 1994
Range for Roman Numeral is [1, 3999]

**Comment by harshbhagwani94** [comment]
Can someone assign this issue to me?

**Comment by sawyer1997** [comment]
Would like to try.

**Comment by Ajordat** [comment]
I can take care of this in Python.

**Comment by Archie4575** [comment]
I'd have a go in C++, if you want.

**Comment by aditya109** [comment]
Hi @Ajordat @Archie4575 @sawyer1997 @sawyer1997 @harshbhagwani94 ! Please go on ahead and raise a PR for the same, linking this issue. I am assigning this issue to you guys. Please consider starring the repo, if you have not already to encourage further contributions.

**Comment by sawyer1997** [comment]
Hi @aditya109 , please consider reviewing the PR and merging the same.

**Comment by Sumit2399** [comment]
Hi,@aditya109.Can I work on the issue With Java.Looking forward to the reply.
