### ISSUE TITLE
Counting occurrence of each word (Python)

### ISSUE THREAD

**Issue by nazuk27** [aditya109/git-osp-for-beginners#276]
You are given 'n' words. Some words may repeat. For each word, output its number of occurrences. The output order should correspond with the input order of appearance of the word. See the sample input/output for clarification.

**Constraints:**
The sum of the lengths of all the words do not exceed 10^6.
All the words are composed of lowercase English letters only.

**Input Format:**
The first line contains the integer, n.
The next n lines each contain a word.

**Output Format:**
Output 2 lines.
On the first line, output the number of distinct words from the input.
On the second line, output the number of occurrences for each distinct word according to their appearance in the input.

**Sample Input:**
4
bcdef
abcdefg
bcde
bcdef

**Sample Output:**
3
2 1 1

**Explanation:**
There are 3 distinct words. Here, "bcdef" appears twice in the input at the first and last positions. The other words appear once each. The order of the first appearances are "bcdef", "abcdefg" and "bcde" which corresponds to the output.

**Comment by nazuk27** [comment]
@aditya109 Can you please assign this to me?

**Comment by aditya109** [comment]
Hi @nazuk27 ! Please go on ahead and raise a PR for the same, linking this issue. I am assigning this issue to you. Please consider starring the repo, if you have not already to encourage further contributions.

**Comment by purva-saxena** [comment]
can you please assign this task to me?? or can anyone please assign this task to me?
