### ISSUE TITLE
Leibniz's formula for calculating pi

### ISSUE THREAD

**Issue by Archie4575** [aditya109/git-osp-for-beginners#278]
The following formula is named after Gottfried Wilhelm von Leibniz, a prominent German polymath who lived from 1646-1716.

![Leibniz pattern](https://wikimedia.org/api/rest_v1/media/math/render/svg/fab3e3e4febf987b57159d81fd47995fb0af1240)

or

![Leibniz sigma](https://encrypted-tbn0.gstatic.com/images?q=tbn%3AANd9GcRserFpj4mpKY4syeu8Tc4A8GLkN8r0RsApTjV6fUyQMiZwxil8)

This program will iterate over this pattern '_k_' times, with '_k_' being defined by the user. The larger the value of '_k_',
the closer the approximation of pi. 

I already have already made a stand-alone C++ program! [here](https://github.com/Archie4575/leibnitz), which I will convert to a function and add to this project. This function prototype will be as follows:

```cpp
long double leibniz(int k);
```

If someone wants to do the same with another language, feel free.

**Comment by aditya109** [comment]
Hi @Archie4575 ! Please go on ahead and raise a PR for the same, linking this issue. I am assigning this issue to you. Please consider starring the repo, if you have not already to encourage further contributions.

**Comment by Archie4575** [comment]
Yeah, sweet. Should I leave the thread open for those who might want to write it in another language? @aditya109

**Comment by gustavoplenamente** [comment]
I would like to add content to this issue in C, Java, Python and Javascript.

**Comment by hryxna** [comment]
@aditya109 I would like to give it a try as well 😄.
@Archie4575 I have a doubt regarding the formula, So basically we have to implement the formula in a loop running "K" times, and then we have to check our ans for the approximation correct? 😅.
Correct me if I'm getting the wrong idea

**Comment by hryxna** [comment]
we can also use recursion if I'm not wrong 🤔

**Comment by Archie4575** [comment]
@hryxna yeah just loop it. You can divide your answer by the actual Pi to get a percentage accuracy if you want. Also I’m not sure if using recursion would be advantageous and it also might run into a maximum recursion depth.

**Comment by Archie4575** [comment]
@gustavoplenamente yeah go ahead. Don’t worry about a version standard.

**Comment by gustavoplenamente** [comment]
Yeah, recursion would add space complexity to the solution.

**Comment by hryxna** [comment]
Don't worry @Archie4575  & @gustavoplenamente  I won't just directly go for recursion though 😬.
Because even I know it may cause an error for higher inputs so Best Case Scenario is a loop and run-time complexity would be O(n) in that case 😁

**Comment by purva-saxena** [comment]
can you please assign this task to me??
