### ISSUE TITLE
Display Highest Runs Scored (Golang)

### ISSUE THREAD

**Issue by aditya109** [aditya109/git-osp-for-beginners#28]
Write a Program to store runs scored by 11 cricketers of Premier League along with their names. Now display the name of highest scoring cricketer who has made the highest score along with runs.

**Comment by Tripathi-Alok** [comment]
Can you assign this to me?

**Comment by aditya109** [comment]
Hi @Tripathi-Alok !  Sure please go ahead and resolve this issue. I will assign this issue to you. A humble request to star this repo to encourage further contributions.   Sure please go ahead and resolve this issue. I will assign this issue to you. A humble request to star this repo to encourage further contributions.
