### ISSUE TITLE
Reverse a doubly linked list (Python)

### ISSUE THREAD

**Issue by nazuk27** [aditya109/git-osp-for-beginners#283]
Given a pointer to the **_head_** node of a doubly linked list, reverse the order of the nodes in the list and display the reversed Linked List.

**Input Format:**
The first line contains an integer **_'t'_**, the number of test cases.
Each test case is of the following format:

> The first line contains an integer **_n_,** the number of elements in the linked list.

> The next **_n_,** lines contain an integer each denoting an element of the linked list.

**Output Format:**
Print the reversed doubly linked list.

**Sample Input:**
1
4
1
2
3
4

**Sample Output:**
4 3 2 1

**Comment by nazuk27** [comment]
@aditya109 Can you please assign this to me? Thanks!

**Comment by aditya109** [comment]
Hi @nazuk27 ! Please go on ahead and raise a PR for the same, linking this issue. I am assigning this issue to you. Please consider starring the repo, if you have not already to encourage further contributions.

**Comment by MalEl-94** [comment]
@nazuk27  Can you please assign this to me. I'd like to attempt this in Java.

**Comment by hryxna** [comment]
I already have implemented this as well @aditya109 & @MalEl-94 in JAVA 😁.

**Comment by harshbhagwani94** [comment]
@aditya109 can you assign this issue to me as well? I want to do this in C++.

**Comment by purva-saxena** [comment]
i would like to solve this issue!
can you please assign it to me
