### ISSUE TITLE
Add 10 beginner level Problems

### ISSUE THREAD

**Issue by rishirajpurohit** [aditya109/git-osp-for-beginners#3]
Because of the increased interest in the repository, we want to add beginner level problems.

To successfully close this, you need to add 10 problem statements following the pattern already used in repository.

**Comment by rishirajpurohit** [comment]
@aditya109 can you assign this one to me.

**Comment by aditya109** [comment]
@rishirajpurohit Thanks !

**Comment by aditya109** [comment]
@rishirajpurohit A humble request : please consider starring the repo to encourage more contributions.

**Comment by rishirajpurohit** [comment]
> @rishirajpurohit A humble request : please consider starring the repo to encourage more contributions.

Done, also, your readme looks great. Interested in adding it to a list of ReadMe files created by Pros? If yes, I'd greatly appreciate if you open a PR here : https://github.com/rishirajpurohit/ReadMePros

**Comment by Hinal-Srivastava** [comment]
@aditya109  can I add a few pattern problems?

**Comment by jyotiGambhir** [comment]
I would lke to add beginner level problems in CPP. Please assign it to me.

**Comment by rishirajpurohit** [comment]
Hey there, sorry I didn't get a chance to work on this, let's assign it to someone else from above

**Comment by Hinal-Srivastava** [comment]
> @aditya109 can I add a few pattern problems in python?
> I am thinking of making a folder specifically for it. It can be helpful.

I'm still up for this👍

**Comment by aditya109** [comment]
> @aditya109 can I add a few pattern problems in python?
> I am thinking of making a folder specifically for it. It can be helpful.

Sure @Hinal-Srivastava please go ahead and create issue relative to them. I will assign labels and milestone to the same.

**Comment by aditya109** [comment]
> I would lke to add beginner level problems in CPP. Please assign it to me.

Hi @jyotiGambhir Ok then I am assigning this to you as well. Please consider starring the repo to encourage more contributions.

**Comment by aditya109** [comment]
> > @rishirajpurohit A humble request : please consider starring the repo to encourage more contributions.
> 
> Done, also, your readme looks great. Interested in adding it to a list of ReadMe files created by Pros? If yes, I'd greatly appreciate if you open a PR here : https://github.com/rishirajpurohit/ReadMePros

Sure why not ! I'll check the repo out.

**Comment by Avantikaa** [comment]
Do the problems covered across all the current 4 languages need to be the same?
Or for each language, we can contribute to the problem solutions independently?

**Comment by gayatripalkar** [comment]
Hi, can I work on this, I will work on beginner level problems in Java, Cpp and Python

**Comment by aditya109** [comment]
> Do the problems covered across all the current 4 languages need to be the same?
> Or for each language, we can contribute to the problem solutions independently?

Hi @Avantikaa ! So the idea is to open similar issues in such a way that people from varying programming background can participate. So it is good to have separate issue for similar problems and people can make it in their own ways in language they are most comfortable.

**Comment by aditya109** [comment]
> Hi, can I work on this, I will work on beginner level problems in Java, Cpp and Python

Hi @gayatripalkar ! Sure you can. I will assign this issue to you. A humble request to star this repo to encourage further contributions.
