### ISSUE TITLE
Maximum Gap

### ISSUE THREAD

**Issue by harshbhagwani94** [aditya109/git-osp-for-beginners#309]
Given an unsorted array, find the maximum difference between the successive elements in its sorted form.

Return 0 if the array contains less than 2 elements.

Example 1:

Input: [3,6,9,1]
Output: 3
Explanation: The sorted form of the array is [1,3,6,9], either
             (3,6) or (6,9) has the maximum difference 3.

Example 2:

Input: [10]
Output: 0
Explanation: The array contains less than 2 elements, therefore return 0.

**Comment by harshbhagwani94** [comment]
@aditya109 Can you assign this issue to me? I want to  do this in C++

**Comment by vikrantkode** [comment]
can you assign this issue to me , i want to do it in java

**Comment by sawyer1997** [comment]
Hi @aditya109,  I am up for python and Golang.

**Comment by Sumit2399** [comment]
Hi, I would love to work on the issue because it would be a good practice for DSA.

**Comment by farFromShallow101** [comment]
Hi, I really want to take this issue as I am a total newbie in open source. I will contribute in C++ language.

**Comment by aditya109** [comment]
Hi @sawyer1997 @harshbhagwani94 @vikrantkode @Sumit2399 @farFromShallow101 ! Please go on ahead and raise a PR for the same, linking this issue. I am assigning this issue to you guys. Please consider starring the repo, if you have not already to encourage further contributions.

**Comment by Sumit2399** [comment]
@aditya109 already made a PR request.Hoping you will merge it soon.

**Comment by gaurisharma360** [comment]
#312 made a c program regarding the above problem . Kindly consider.

**Comment by 0ChanAk** [comment]
Hi I want to solve this in PHP and apex. Please assign it to me. thanks.

**Comment by MalEl-94** [comment]
Hi, i'd like to try this in Java.

**Comment by vijaykrishna536** [comment]
Hi @aditya109 
#325 made programme in javascript for the same
Hope to get it reviewed soon

**Comment by manralhemant10** [comment]
can you assign this issue to me, I would like to contribute in c++

**Comment by ltsaiete** [comment]
Hi @aditya109 , can assign this issue to me?
I would like to do it in JavaScript.

**Comment by pratyush-patwa** [comment]
Hi @aditya109  , could you please assign this issue to me?
I would like to do this in Java with optimal Solution

**Comment by harshbhagwani94** [comment]
@farFromShallow101 I already raised the solution to this since morning

**Comment by PolarBear-289** [comment]
can u assign this issue to me, I would like to do t in c++

**Comment by Utkarsh299-tech** [comment]
Hi, @aditya109 I would like to solve this in Python in a linear time/space. Could you please assign this issue to me?

**Comment by tushar14041** [comment]
Hi, @aditya109  can you assign this to me, I will solve this in C language

**Comment by DilshanDeAlmeida** [comment]
hi @aditya109 assign me to this issue. I have implemented a working in python.

**Comment by tanishq-1011** [comment]
hi... kindly assign me.. i have working code in python

**Comment by trishitapingolia** [comment]
@aditya109 can you plz review my pr??

**Comment by calingeorgeadrian** [comment]
Can you please assign me to this issue? I want to do it in C#.
