### ISSUE TITLE
Longest Substring Without Repeating Characters(C++)

### ISSUE THREAD

**Issue by prakharpande** [aditya109/git-osp-for-beginners#339]
Problem Statement:
Given a string s, find the length of the longest substring without repeating characters.

Constraints:
0 <= s.length <= 5 * 104
s consists of English letters, digits, symbols and spaces.

Example 1:
Input: s = "abcabcbb"
Output: 3
Explanation: The answer is "abc", with the length of 3.

Input: s = "aaaaa"
Output: 1
Explanation: The answer is "b", with a length of 1.

**Comment by prakharpande** [comment]
Please assign this issue to me. I will work on this in c++.

**Comment by pratyush-patwa** [comment]
Hey @prakharpande could you please assign this issue to me. I will work on this in Java.

**Comment by luhcasgabriel** [comment]
pode atribuir esse problema para mim ? vou fazer em JS
