### ISSUE TITLE
[Dutch National Flag]

### ISSUE THREAD

**Issue by pratyush-patwa** [aditya109/git-osp-for-beginners#340]
We have an array consisting of  only 0, 1 & 2. We have to sort the array in the linear time complexity. 

Example: 
Input array = [  0, 2, 2, 1, 2, 0, 1, 1 ]
Output  =  [0, 0, 1, 1, 1, 2, 2, 2 ]

**Comment by Sumit2399** [comment]
Hi @pratyush-patwa , can I work on the issue?

**Comment by phast184** [comment]
Hi I would like to work on this
