### ISSUE TITLE
To check if a number is an Armstrong number

### ISSUE THREAD

**Issue by 420-Madhav** [aditya109/git-osp-for-beginners#351]
An Armstrong number is a number that is equal to the sum of cubes of its digits. For example 0, 1, 153, 370, 371 and 407 are  Armstrong numbers.

**Comment by 420-Madhav** [comment]
Can you please assign this issue to me?

**Comment by DilshanDeAlmeida** [comment]
hi @420-Madhav  assign me to this issue. I have implemented a working in python.

**Comment by SauravBaba** [comment]
@420-Madhav assign to me, I done it

**Comment by DilshanDeAlmeida** [comment]
> hi @420-Madhav assign me to this issue. I have implemented a working in python.

created a pull request for you to accept :)

**Comment by 96RadhikaJadhav** [comment]
Can I do this in python?
