### ISSUE TITLE
To check if a number is a pallindrome

### ISSUE THREAD

**Issue by 420-Madhav** [aditya109/git-osp-for-beginners#352]
A Pallindrome number is a number which is equal to its reverse.
Eg : 454, 1, 13531, 707

**Comment by 420-Madhav** [comment]
Can you please assign this issue to me

**Comment by laasyasree** [comment]
Can I work on this?

**Comment by Mahima7120** [comment]
Reverse and compare

**Comment by subhadeep-123** [comment]
can i solve this issue

**Comment by silvasobrinho** [comment]
can i work on this in C#?

**Comment by 96RadhikaJadhav** [comment]
Can I do this in python?
