### ISSUE TITLE
Convert a decimal number to its binary equivalent. 

### ISSUE THREAD

**Issue by 420-Madhav** [aditya109/git-osp-for-beginners#356]
Provide a solution for this in C++

**Comment by RohanTheProgrammer** [comment]
I want to work on this. Please assign it to me

**Comment by RohanTheProgrammer** [comment]
Can you specify that should that the program have to convert only integers or decimal numbers too

**Comment by 420-Madhav** [comment]
We only talk of integers when it comes to conversion from one number system to another @RohanTheProgrammer

**Comment by RohanTheProgrammer** [comment]
I can create this program

Please assign it to me @420-Madhav

**Comment by ViKrAm-Bais** [comment]
@aditya109 could you assign this to me, I have an solution for this ?
