### ISSUE TITLE
Two Sum

### ISSUE THREAD

**Issue by sommano** [aditya109/git-osp-for-beginners#375]
Given an array of integers nums and an integer target, return indices of the two numbers such that they add up to target.

You may assume that each input would have exactly one solution, and you may not use the same element twice.

You can return the answer in any order.

Example 3:

Input: nums = [3,3], target = 6
Output: [0,1]

**Comment by felix-chin** [comment]
@sommano I would like to attempt this, can you please assign to me.

**Comment by 96RadhikaJadhav** [comment]
I want to try this in python..Could you please assign it to me?

**Comment by RatulDawar** [comment]
I would like to attempt it can you assign me(Java)
