### ISSUE TITLE
[Rearrange an array with O(1) extra space]

### ISSUE THREAD

**Issue by 0ChanAk** [aditya109/git-osp-for-beginners#387]
Given an array arr[] of size N where every element is in the range from 0 to n-1. Rearrange the given array so that arr[i] becomes arr[arr[i]] in O(1) extra space.

Input:
N = 5
arr[] = {4,0,2,1,3}
Output: 3 4 2 0 1
Explanation: arr[0] = 4 and arr[arr[0]] 
= 3. Also, arr[1] = 0 and arr[arr[1]] 
= 4 and so on. So, rearranging elements,
we get array as 3 4 2 0 1.

@aditya109  can I work on this?

**Comment by codeRider686** [comment]
plz assign me this issue
