### ISSUE TITLE
Count Digits (Java)

### ISSUE THREAD

**Issue by namitmalasi** [aditya109/git-osp-for-beginners#39]
Hi @namitmalasi Could you open a relative issue for this please and link it here ? I will tag with `Hacktoberfest`.

_Originally posted by @aditya109 in https://github.com/aditya109/git-osp-for-beginners/pull/37#issuecomment-703249986_

**Comment by aditya109** [comment]
Hi @namitmalasi Please change the issue title to something sane and please add a description.

**Comment by aditya109** [comment]
Write a program to count the digits of the entered integer.

**Comment by mohdarif8299** [comment]
Can you assign this to me?

**Comment by nikinegi1998** [comment]
Please assign this to me

**Comment by gayatripalkar** [comment]
Hi, Can you assign this to me.

**Comment by neha07kumari** [comment]
Can i work on this issue? Please assign it to me. @aditya109

**Comment by Akanksha810** [comment]
Can you assign it to me?

**Comment by govindraj111** [comment]
Hey @aditya109 could you assign this to me?
Thanks in advance!
