### ISSUE TITLE
Container With Most Water [C++ solution required]

### ISSUE THREAD

**Issue by aditya109** [aditya109/git-osp-for-beginners#397]
Given n non-negative integers a1, a2, ..., an , where each represents a point at coordinate (i, ai). n vertical lines are drawn such that the two endpoints of the line i is at (i, ai) and (i, 0). Find two lines, which, together with the x-axis forms a container, such that the container contains the most water.

Notice that you may not slant the container.

 

Example 1:

Input: height = [1,8,6,2,5,4,8,3,7]
Output: 49
Explanation: The above vertical lines are represented by array [1,8,6,2,5,4,8,3,7]. In this case, the max area of water (blue section) the container can contain is 49.
Example 2:

Input: height = [1,1]
Output: 1
Example 3:

Input: height = [4,3,2,1,4]
Output: 16
Example 4:

Input: height = [1,2,1]
Output: 2

**Comment by Stellar-X** [comment]
Can I be assigned this please? I can provide the solution in C++.

**Comment by aditya109** [comment]
Hi @Stellar-X ! Happy to receive contribution such early. I have assigned this issue to you. Happy hacking !

**Comment by Stellar-X** [comment]
@aditya109 , I have completed the solution for the problem in C++ and commented the code for easy explanation. 
Can you specify where do I need to commit my code to in my branch? Like in some specific folder or in the master branch as it is.
Also, I have two solutions for the same problem present with me, one is O(n^2) and other is O(n). So, should I add only the most efficient one or both solutions?

**Comment by aditya109** [comment]
Hi @Stellar-X ! Just add the better one !
For info related to contribution, refer to [CONTRIBUTING.md](https://github.com/aditya109/git-osp-for-beginners/blob/master/CONTRIBUTING.md).
It has all the steps regarding the above.

**Comment by Stellar-X** [comment]
@aditya109 , I have created the pull request, so do please check it. Also, please provide the feedback if there is any issue or if something more is needed to be added.
Thank you for the opportunity !!

**Comment by aditya109** [comment]
This issue was solved by @Stellar-X , the PR was successfully merged ! Thereby, closing this issue !
