### ISSUE TITLE
Display Prime Array Elements (Python)

### ISSUE THREAD

**Issue by aditya109** [aditya109/git-osp-for-beginners#4]
Problem : Write a Program to store 20 numbers in an array and display only those numbers which are prime.

**Comment by Hinal-Srivastava** [comment]
I'll do it👍

**Comment by aditya109** [comment]
@Hinal-Srivastava Ok then I am assigning this to you. Please consider starring the repo to encourage more contributions.

**Comment by Hinal-Srivastava** [comment]
> @Hinal-Srivastava Ok then I am assigning this to you. Please consider starring the repo to encourage more contributions.

You haven't assigned it to me yet however, I'll proceed on my end.

**Comment by aditya109** [comment]
Ohh I apologise ! I self-assigned this issue instead of assigning it you 😞

**Comment by aditya109** [comment]
> > @Hinal-Srivastava Ok then I am assigning this to you. Please consider starring the repo to encourage more contributions.
> 
> You haven't assigned it to me yet however, I'll proceed on my end.

Yea sure.

**Comment by Hinal-Srivastava** [comment]
> Ohh I apologise ! I self-assigned this issue instead of assigning it you 😞

Its alright 🙌🏼
