### ISSUE TITLE
Added Grading Students Solution (Python)

### ISSUE THREAD

**Issue by deepsingh132** [aditya109/git-osp-for-beginners#40]
Please Assign it to me.

**Comment by aditya109** [comment]
Hi @deepsingh132 ! Sure please go ahead and resolve this issue. I will assign this issue to you. A humble request to star this repo to encourage further contributions.

**Comment by aditya109** [comment]
Also please add a language in braces in your issue's tag. C++, Python, Java, Golang

**Comment by deepsingh132** [comment]
I've made a pr please do check it out
