### ISSUE TITLE
Generate Parentheses [C++-Solution required]

### ISSUE THREAD

**Issue by aditya109** [aditya109/git-osp-for-beginners#419]
Given `n` pairs of parentheses, write a function to *generate all combinations of well-formed parentheses*.

**Example 1:**

```
Input: n = 3
Output: ["((()))","(()())","(())()","()(())","()()()"]
```

**Example 2:**

```
Input: n = 1
Output: ["()"]
```

 

**Constraints:**

- `1 <= n <= 8`

Reference: https://leetcode.com/problems/generate-parentheses/

**Comment by tamal-kundu** [comment]
i can solve this issue ..can u plzz assign me?

**Comment by aditya109** [comment]
Hi @tamal-kundu ! I have assigned this issue to you. Before raising a PR, please take a look at CONTRIBUTING.md and follow the guidelines. Also, if it is not too much to ask, please consider starring ⭐ the repository. It helps boost the repo popularity and guide more people towards active contribution. That is all. Happy hacking !

**Comment by vansh-kapila** [comment]
I have written the code for the issue in the required language. Kindly have a look at it. #495

**Comment by aditya109** [comment]
Reopening this issue for other contributors !

**Comment by aditya109** [comment]
As it has been 8 days and no response from the previous assignee, hence clearing the assignee @tamal-kundu ! 💔

**Comment by MashTerro** [comment]
@aditya109 I also want to work on this issue can you please assign me?
