### ISSUE TITLE
Generate Parentheses [Golang-Solution required]

### ISSUE THREAD

**Issue by aditya109** [aditya109/git-osp-for-beginners#421]
Given `n` pairs of parentheses, write a function to *generate all combinations of well-formed parentheses*.

**Example 1:**

```
Input: n = 3
Output: ["((()))","(()())","(())()","()(())","()()()"]
```

**Example 2:**

```
Input: n = 1
Output: ["()"]
```

 

**Constraints:**

- `1 <= n <= 8`

Reference: https://leetcode.com/problems/generate-parentheses/

**Comment by MashTerro** [comment]
I want to work on this issue could you please assign me

**Comment by pranjalg13** [comment]
Hey, @aditya109 I am taking this since recently started learning GO , might be helpful to practice :).
