### ISSUE TITLE
Generate Parentheses [Java-Solution required]

### ISSUE THREAD

**Issue by aditya109** [aditya109/git-osp-for-beginners#422]
Given `n` pairs of parentheses, write a function to *generate all combinations of well-formed parentheses*.

**Example 1:**

```
Input: n = 3
Output: ["((()))","(()())","(())()","()(())","()()()"]
```

**Example 2:**

```
Input: n = 1
Output: ["()"]
```

 

**Constraints:**

- `1 <= n <= 8`

Reference: https://leetcode.com/problems/generate-parentheses/

**Comment by tamal-kundu** [comment]
i can solve this issue ..can u plzz assign me?

**Comment by sbaijal** [comment]
Please assign this issue to me @aditya109 ...
I am in my 5th semester and preparing these types of questions..
Will update the solution as fast as possible.

**Comment by aditya109** [comment]
Hi @sbaijal !  have assigned this issue to you. Before raising a PR, please take a look at CONTRIBUTING.md and follow the guidelines. Also, if it is not too much to ask, please consider starring ⭐ the repository. It helps boost the repo popularity and guide more people towards active contribution. That is all. Happy hacking !

**Comment by aditya109** [comment]
As it has been 7 days and no response from the previous assignee, hence clearing the assignee @sbaijal ! 💔

**Comment by aditya109** [comment]
Hi @akankshatyagiat ! Sure thing. I have assigned this issue to you.
Before raising a PR, please take a look at [CONTRIBUTING.md](https://github.com/aditya109/git-osp-for-beginners/blob/master/CONTRIBUTING.md) and follow the guidelines.
Also, if it is not too much to ask, please consider starring [⭐](https://emojipedia.org/star/) the repository. It helps boost the repo popularity and guide more people towards active contribution. That is all. Happy hacking !
