### ISSUE TITLE
  Generate Parentheses [Javascript-Solution required]

### ISSUE THREAD

**Issue by aditya109** [aditya109/git-osp-for-beginners#423]
Given `n` pairs of parentheses, write a function to *generate all combinations of well-formed parentheses*.

**Example 1:**

```
Input: n = 3
Output: ["((()))","(()())","(())()","()(())","()()()"]
```

**Example 2:**

```
Input: n = 1
Output: ["()"]
```

 

**Constraints:**

- `1 <= n <= 8`

Reference: https://leetcode.com/problems/generate-parentheses/

**Comment by NisargChokshi** [comment]
@aditya109 Can you assign this to me?

**Comment by NisargChokshi** [comment]
@aditya109 I have Added the solution for the given problem of Generate Parenthesis using JavaScript.

After referring and following the [Contributing Guildelines](https://github.com/aditya109/git-osp-for-beginners/blob/master/CONTRIBUTING.md), I have created a PR. 

Please review and share your thoughts on the same.
https://github.com/aditya109/git-osp-for-beginners/pull/443

**Comment by aditya109** [comment]
This issue was solved by @NisargChokshi , the PR was successfully merged ! Thereby, closing this issue !
