### ISSUE TITLE
Combination Sum [C++-Solution required]

### ISSUE THREAD

**Issue by aditya109** [aditya109/git-osp-for-beginners#426]
Given an array of **distinct** integers `candidates` and a target integer `target`, return *a list of all **unique combinations** of* `candidates` *where the chosen numbers sum to* `target`*.* You may return the combinations in **any order**.

The **same** number may be chosen from `candidates` an **unlimited number of times**. Two combinations are unique if the frequency of at least one of the chosen numbers is different.

It is **guaranteed** that the number of unique combinations that sum up to `target` is less than `150` combinations for the given input.

 

**Example 1:**

```
Input: candidates = [2,3,6,7], target = 7
Output: [[2,2,3],[7]]
Explanation:
2 and 3 are candidates, and 2 + 2 + 3 = 7. Note that 2 can be used multiple times.
7 is a candidate, and 7 = 7.
These are the only two combinations.
```

**Example 2:**

```
Input: candidates = [2,3,5], target = 8
Output: [[2,2,2,2],[2,3,3],[3,5]]
```

**Example 3:**

```
Input: candidates = [2], target = 1
Output: []
```

**Example 4:**

```
Input: candidates = [1], target = 1
Output: [[1]]
```

**Example 5:**

```
Input: candidates = [1], target = 2
Output: [[1,1]]
```

 

**Constraints:**

- `1 <= candidates.length <= 30`
- `1 <= candidates[i] <= 200`
- All elements of `candidates` are **distinct**.
- `1 <= target <= 500`

Reference: https://leetcode.com/problems/combination-sum/

**Comment by hortiprajwal** [comment]
`     
          class Solution {
                 public:

              vector<vector<int>>result;
              vector<int>current;

        void function(vector<int>& candidates,int target,int index)
        {
              if(target==0){
              result.push_back(current);
              return;
        }
    
    if(index==candidates.size() || target<0)return;
    
       current.push_back(candidates[index]);
       function(candidates,target-candidates[index],index);
       current.pop_back();
       function(candidates,target,index+1);      
    }

    vector<vector<int>> combinationSum(vector<int>& candidates, int target) {
          function(candidates,target,0);
          return result;
    }
};`

**Comment by tamal-kundu** [comment]
i can solve this issue ..can u plzz assign me?

**Comment by ayush523** [comment]
Hi.I would like to work on this issue.

**Comment by aditya109** [comment]
Hi @ayush523 @tamal-kundu !  I have assigned this issue to you both. Before raising a PR, please take a look at CONTRIBUTING.md and follow the guidelines. Also, if it is not too much to ask, please consider starring ⭐ the repository. It helps boost the repo popularity and guide more people towards active contribution. That is all. Happy hacking !

**Comment by ayush523** [comment]
Hi @aditya109 ,for some reason I am not able to clone the repository.The error I am getting:
fatal: unable to checkout working tree
warning: Clone succeeded, but checkout failed.

**Comment by aditya109** [comment]
Hi @ayush523 ! Not sure what the issue is:
```sh
>: git clone https://github.com/aditya109/git-osp-for-beginners
Cloning into 'git-osp-for-beginners'...
remote: Enumerating objects: 1731, done.
remote: Counting objects: 100% (250/250), done.
remote: Compressing objects: 100% (154/154), done.
remote: Total 1731 (delta 137), reused 156 (delta 81), pack-reused 1481
Receiving objects: 100% (1731/1731), 387.24 KiB | 667.00 KiB/s, done.
Resolving deltas: 100% (762/762), done.
```

**Comment by ayush523** [comment]
I have opened a discussion

**Comment by aditya109** [comment]
Let a comment on the same. Please check @ayush523 !

**Comment by ayush523** [comment]
I am able to clone now.Thanks

**Comment by aditya109** [comment]
This issue was solved by @ayush523 , the PR was successfully merged ! Thereby, closing this issue
