### ISSUE TITLE
Please add the hactoberfest-accepted topic otherwise the participants' contributions will not be counted as as successful contribution in hactoberfest2021

### ISSUE THREAD

**Issue by tamal-kundu** [aditya109/git-osp-for-beginners#440]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by aditya109** [comment]
Hi @tamal-kundu ! There is a label for that, which is given to PR once it is merged successfully.
Also, this is not required for your `Hacktoberfest` contribution to be counted as successful.
Closing this issue as it is not required. 
Please re-open the issue if further clarification is required.
