### ISSUE TITLE
Merge Sorted Array [C-Solution required]

### ISSUE THREAD

**Issue by aditya109** [aditya109/git-osp-for-beginners#447]
You are given two integer arrays `nums1` and `nums2`, sorted in **non-decreasing order**, and two integers `m` and `n`, representing the number of elements in `nums1` and `nums2` respectively.

**Merge** `nums1` and `nums2` into a single array sorted in **non-decreasing order**.

The final sorted array should not be returned by the function, but instead be *stored inside the array* `nums1`. To accommodate this, `nums1` has a length of `m + n`, where the first `m` elements denote the elements that should be merged, and the last `n` elements are set to `0` and should be ignored. `nums2` has a length of `n`.

 

**Example 1:**

```
Input: nums1 = [1,2,3,0,0,0], m = 3, nums2 = [2,5,6], n = 3
Output: [1,2,2,3,5,6]
Explanation: The arrays we are merging are [1,2,3] and [2,5,6].
The result of the merge is [1,2,2,3,5,6] with the underlined elements coming from nums1.
```

**Example 2:**

```
Input: nums1 = [1], m = 1, nums2 = [], n = 0
Output: [1]
Explanation: The arrays we are merging are [1] and [].
The result of the merge is [1].
```

**Example 3:**

```
Input: nums1 = [0], m = 0, nums2 = [1], n = 1
Output: [1]
Explanation: The arrays we are merging are [] and [1].
The result of the merge is [1].
Note that because m = 0, there are no elements in nums1. The 0 is only there to ensure the merge result can fit in nums1.
```

 

**Constraints:**

- `nums1.length == m + n`
- `nums2.length == n`
- `0 <= m, n <= 200`
- `1 <= m + n <= 200`
- `-109 <= nums1[i], nums2[j] <= 109`

Reference Link: [(1) Merge Sorted Array - LeetCode](

**Comment by NidhiNivedita6** [comment]
Could you please assign this to me @aditya109

**Comment by aditya109** [comment]
HI @NidhiNivedita6 ! I have assigned this issue to you. Before raising a PR, please take a look at CONTRIBUTING.md and follow the guidelines. Also, if it is not too much to ask, please consider starring ⭐ the repository. It helps boost the repo popularity and guide more people towards active contribution. That is all. Happy hacking !

**Comment by Sheikh-Yawar** [comment]
Hey, can I work on this issue

**Comment by aditya109** [comment]
As it has been >7 days and no response from the previous assignee, hence clearing the assignee @NidhiNivedita6 ! 💔

**Comment by aditya109** [comment]
This issue was solved by @Sheikh-Yawar , the PR was successfully merged ! 
Thereby, closing this issue !
