### ISSUE TITLE
Different runs scored by the batsmen in a team in Cricket

### ISSUE THREAD

**Issue by Rahul171201** [aditya109/git-osp-for-beginners#45]
#28 Write a Program to store runs scored by 11 cricketers of Premier League along with their names. Now display the name of highest scoring cricketer who has made the highest score along with runs...

**Comment by reejuBhattacharya** [comment]
Working on it in Java

**Comment by Rahul171201** [comment]
Ok go ahead!

**Comment by rashrey2308** [comment]
Can I implement one in cpp?

**Comment by Rahul171201** [comment]
Ok @rashrey2308 you can too give it a go!
