### ISSUE TITLE
Merge Sorted Array [Javascript-Solution required]

### ISSUE THREAD

**Issue by aditya109** [aditya109/git-osp-for-beginners#450]
You are given two integer arrays `nums1` and `nums2`, sorted in **non-decreasing order**, and two integers `m` and `n`, representing the number of elements in `nums1` and `nums2` respectively.

**Merge** `nums1` and `nums2` into a single array sorted in **non-decreasing order**.

The final sorted array should not be returned by the function, but instead be *stored inside the array* `nums1`. To accommodate this, `nums1` has a length of `m + n`, where the first `m` elements denote the elements that should be merged, and the last `n` elements are set to `0` and should be ignored. `nums2` has a length of `n`.

 

**Example 1:**

```
Input: nums1 = [1,2,3,0,0,0], m = 3, nums2 = [2,5,6], n = 3
Output: [1,2,2,3,5,6]
Explanation: The arrays we are merging are [1,2,3] and [2,5,6].
The result of the merge is [1,2,2,3,5,6] with the underlined elements coming from nums1.
```

**Example 2:**

```
Input: nums1 = [1], m = 1, nums2 = [], n = 0
Output: [1]
Explanation: The arrays we are merging are [1] and [].
The result of the merge is [1].
```

**Example 3:**

```
Input: nums1 = [0], m = 0, nums2 = [1], n = 1
Output: [1]
Explanation: The arrays we are merging are [] and [1].
The result of the merge is [1].
Note that because m = 0, there are no elements in nums1. The 0 is only there to ensure the merge result can fit in nums1.
```

 

**Constraints:**

- `nums1.length == m + n`
- `nums2.length == n`
- `0 <= m, n <= 200`
- `1 <= m + n <= 200`
- `-109 <= nums1[i], nums2[j] <= 109`

Reference Link: [(1) Merge Sorted Array - LeetCode](

**Comment by mani-rsg** [comment]
Hi @aditya109 , Can you please assign me?

**Comment by mani-rsg** [comment]
Have raised pull request for the same 😄

**Comment by aditya109** [comment]
Hi @mani-rsg ! I have assigned this issue to you. 
I maintain this repository as a hobby, and don't get much time for repo maintenance work apart from my full-time work. 
I am sorry about getting back to you so late. Hope you understand.
Also, if it is not too much to ask, please consider starring ⭐ the repository. It helps boost the repo popularity and guide more people towards active contribution. That is all. Happy hacking !

**Comment by aditya109** [comment]
This issue was solved by @mani-rsg , the PR was successfully merged ! Thereby, closing this issue !
