### ISSUE TITLE
Palindrome Number [Java-Solution required]

### ISSUE THREAD

**Issue by aditya109** [aditya109/git-osp-for-beginners#456]
Given an integer `x`, return `true` if `x` is palindrome integer.

An integer is a **palindrome** when it reads the same backward as forward. For example, `121` is palindrome while `123` is not.

 

**Example 1:**

```
Input: x = 121
Output: true
```

**Example 2:**

```
Input: x = -121
Output: false
Explanation: From left to right, it reads -121. From right to left, it becomes 121-. Therefore it is not a palindrome.
```

**Example 3:**

```
Input: x = 10
Output: false
Explanation: Reads 01 from right to left. Therefore it is not a palindrome.
```

**Example 4:**

```
Input: x = -101
Output: false
```

 

**Constraints:**

- `-231 <= x <= 231 - 1`

Reference Link: [(1) Palindrome Number - LeetCode](

**Comment by a-ayush19** [comment]
@aditya109 can you assign this to me?

**Comment by NidhiNivedita6** [comment]
Could you please assign this to me? @aditya109

**Comment by aditya109** [comment]
Hi @a-ayush19 !  I have assigned this issue to you. Before raising a PR, please take a look at CONTRIBUTING.md and follow the guidelines. Also, if it is not too much to ask, please consider starring ⭐ the repository. It helps boost the repo popularity and guide more people towards active contribution. That is all. Happy hacking !

**Comment by aditya109** [comment]
Hi @NidhiNivedita6 ! I have assigned this issue to you. Before raising a PR, please take a look at CONTRIBUTING.md and follow the guidelines. Also, if it is not too much to ask, please consider starring star the repository. It helps boost the repo popularity and guide more people towards active contribution. That is all. Happy hacking !

**Comment by aditya109** [comment]
Reopening this issue for other contributors !

**Comment by aditya109** [comment]
This issue was solved by @Brkgng @a-ayush19 @KholoodS , the PR was successfully merged ! 
Thereby, closing this issue !
