### ISSUE TITLE
Display Prime Array Elements (Golang)

### ISSUE THREAD

**Issue by aditya109** [aditya109/git-osp-for-beginners#5]
Problem : Write a Program to store 20 numbers in an array and display only those numbers which are prime.

**Comment by shubhamnag14** [comment]
i'd like to solve this problem using python or c
so can i solve this

**Comment by aditya109** [comment]
@shubhamnag14 I think Python Issue has already been assigned. If you want to do it in C, please take a look at the structure of the repo for Program1. I will create an issue for the same.

**Comment by Adithiyan** [comment]
Please assign me this. I would like to do it in java

**Comment by shubhamnag14** [comment]
i will do in c..and submit by tomorrow

**Comment by ParthPali** [comment]
I can do this in Golang. Please assign me.

**Comment by ParthPali** [comment]
@aditya109  I can do this in Golang. Please assign me

**Comment by aditya109** [comment]
Hi @ParthPali I have assigned this issue to you as well. Please consider starring the repo to encourage more contributions.

**Comment by aditya109** [comment]
Hi @thetkpark I see that you completed the issue. Please consider starring the repo to encourage more contributions.

**Comment by ParthPali** [comment]
> Hi @ParthPali I have assigned this issue to you as well. Please consider starring the repo to encourage more contributions.

Thanks, @aditya109 I have starred the repo.
