### ISSUE TITLE
Roots of the Quadratic Equation | Prime Numbers upto N | Python

### ISSUE THREAD

**Issue by vijay5158** [aditya109/git-osp-for-beginners#53]
Program1 - which takes inputs of the coefficients of a Quadratic Equation and outputs roots of the equation. 
Program2 - which takes input of a number N and outputs all Prime Numbers upto N.

**Comment by vijay5158** [comment]
Please assign this to me

**Comment by aditya109** [comment]
Hi @vijay5158  ! Thanks for opening the issue and following the issue-template. I will assign this issue to you. Also, if you have not, consider starring this repo.

**Comment by vijay5158** [comment]
@aditya109 Please review this pr (#54 ) which I created to solve this issue.

**Comment by titichhm** [comment]
@aditya109 Hi there. Can I solve both the programs in C++? That would be really cool :)
