### ISSUE TITLE
Check given string is valid anagram or not? | CPP

### ISSUE THREAD

**Issue by wayne9499** [aditya109/git-osp-for-beginners#58]
Given two strings say s and t, write a function to determine if t is an [anagram](https://en.wikipedia.org/wiki/Anagram) of s. | CPP
## Example
Input: s = "anagram", t = "nagaram"
Output: True
Input: s = "rat", t = "car"
Output: False

**Comment by wayne9499** [comment]
Please assign to me.

**Comment by IMPrimph** [comment]
@wayne9499 
Assign this to me, I will write the program and send

**Comment by gayatripalkar** [comment]
Hi, can you assign this to me

**Comment by xyther14** [comment]
Can you assign me this problem? I have a unique implementation for this.

**Comment by aditya109** [comment]
Hi @wayne9499 ! Thanks for opening the issue and following the issue-template. I will assign this issue to you.

**Comment by aditya109** [comment]
Hi @gayatripalkar @IMPrimph @xyther14,  I am sorry I can't this issue has already been claimed or merge your PR, but feel free to raise one and link this issue. I will approve your PR and tag it `hacktoberfest-accepted` which carries the same value and will counted in Hacktoberfest stats. Also a humble request could please star the repo, it helps in encouraging contributions.

**Comment by xyther14** [comment]
> Hi @gayatripalkar @IMPrimph @xyther14,  I am sorry I can't this issue has already been claimed or merge your PR, but feel free to raise one and link this issue. I will approve your PR and tag it `hacktoberfest-accepted` which carries the same value and will counted in Hacktoberfest stats. Also a humble request could please star the repo, it helps in encouraging contributions.

Can I raise an issue for doing the same algorithm in Java?

**Comment by gayatripalkar** [comment]
> Hi @gayatripalkar @IMPrimph @xyther14, I am sorry I can't this issue has already been claimed or merge your PR, but feel free to raise one and link this issue. I will approve your PR and tag it `hacktoberfest-accepted` which carries the same value and will counted in Hacktoberfest stats. Also a humble request could please star the repo, it helps in encouraging contributions.

So I am brand new to open source and don't know how to do that, can you guide me?

**Comment by aditya109** [comment]
> > Hi @gayatripalkar @IMPrimph @xyther14, I am sorry I can't this issue has already been claimed or merge your PR, but feel free to raise one and link this issue. I will approve your PR and tag it `hacktoberfest-accepted` which carries the same value and will counted in Hacktoberfest stats. Also a humble request could please star the repo, it helps in encouraging contributions.
> 
> So I am brand new to open source and don't know how to do that, can you guide me?

Sure so what you wanna do is, 
Find a question you like. Open a issue on the same. Claim it for yourself(ask me to assign it you). Follow this [template](https://github.com/aditya109/git-osp-for-beginners/issues/new?assignees=&labels=Hacktoberfest%2C+good+first+issue&template=programming-question.md&title=%5BQuestion%5D). Clone the forked repo.  Raise a PR and link your issue. That's it ! Hope this helps.

**Comment by gayatripalkar** [comment]
Yes thanks
