### ISSUE TITLE
Travelling Salesman Problem using Bit-Masking | CPP

### ISSUE THREAD

**Issue by wayne9499** [aditya109/git-osp-for-beginners#60]
Given a list of cities and the distances between each pair of cities, what is the shortest possible route that visits each city exactly once and returns to the origin city?
[ [0, 20, 42, 25],
 [20, 0, 30, 34],
 [42, 30, 0, 10],
 [25, 34, 10, 0] ]
therefore length of shortest route is 85 (20 + 30 + 10 + 25)

**Comment by wayne9499** [comment]
Assign to me..

**Comment by aditya109** [comment]
Hi @wayne9499 ! Thanks for opening the issue and following the issue-template. I will assign this issue to you. Also, if you have not, consider starring this repo.
