### ISSUE TITLE
Program to Check Whether a Number is Prime or Not | CPP

### ISSUE THREAD

**Issue by Hackerbone** [aditya109/git-osp-for-beginners#75]
Write a program to Check Whether the input number is Prime or Not.

Input: Enter a positive integer : 29
Output: 29 is a prime number.
Input: Enter a positive integer : 12
Output: 12 is not a prime number.

**Comment by Hackerbone** [comment]
Assign me this question pls @aditya109

**Comment by Hackerbone** [comment]
Sent a PR do review and merge if all seems good! Thanks again .. @aditya109

**Comment by shubhamnag14** [comment]
please assign me this issue@aditya109

**Comment by aditya109** [comment]
> please assign me this issue@aditya109

Hi @shubhamnag14 ! I am sorry I can't this issue has already been claimed, but feel free to raise one and link this issue. I will approve your PR and tag it `hacktoberfest-accepted` which carries the same value and will counted in Hacktoberfest stats. Also a humble request could please star the repo, it helps in encouraging contributions.

**Comment by aaksah1234** [comment]
@aditya109,I am new to open source. As asked I have raised an issue & referenced it to this issue . Kindly accept my pr on that issue.

**Comment by abhinavtiwary04** [comment]
Please assign me this issue if not already resolved, @aditya109

**Comment by aditya109** [comment]
> @aditya109, since this issue is already resolved, may I create another issue and link this one to it? Will the PR be considered?

Hi @abhinavtiwary04 try opening a different issue altogether. Try opening something on a question you like.

**Comment by iSpy-u** [comment]
Can I do this in C, Plz assign me

**Comment by Hackerbone** [comment]
I am closing this issue since this program has already been done.
@aditya109
