### ISSUE TITLE
Add the program to convert Celsius to Fahrenheit | Java

### ISSUE THREAD

**Issue by pasan04** [aditya109/git-osp-for-beginners#78]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by lilcoltsmith** [comment]
I would like to work on this issue. Could you please assign it to me?

**Comment by govindraj111** [comment]
Hey @pasan04 . Look into the Pull request https://github.com/aditya109/git-osp-for-beginners/pull/84 raised for this problem.
Thanks in advance!

**Comment by govindraj111** [comment]
@aditya109 Any update on this would be appreciated!
