### ISSUE TITLE
[Question] Find whether two strings are anagrams or not | JAVA

### ISSUE THREAD

**Issue by xyther14** [aditya109/git-osp-for-beginners#83]
Given two strings a and b. The task is to check whether two given strings are anagram of each other or not.

EXAMPLE
geeksforgeeks forgeeksgeeks
TRUE

allergy allergic
FALSE

I've a unique implementation for this question.

**Comment by Kaustav96** [comment]
Can you assign this to me?

**Comment by hryxna** [comment]
hello @xyther14 I would like to share my own solution with you and let me know after reviewing it 😄 
feel free to assign it to me.

**Comment by LiorBitton** [comment]
String.reverse and then check using equals

**Comment by rajitnb** [comment]
Please assign this to me. I have an optimal solution.

**Comment by parthchainani** [comment]
i can do this in c/c++ if u assign it to me

**Comment by hryxna** [comment]
Hello @aditya109, I'm currently implementing Luhn's algorithm to find valid credit-card no.
would it be ok if I add it to this repo?

**Comment by aditya109** [comment]
> Hello @aditya109, I'm currently implementing Luhn's algorithm to find valid credit-card no.
> would it be ok if I add it to this repo?

Sure @hryxna ! Please go ahead. Just follow the `contribution_guidelines.md`. And you should be okay.

**Comment by aditya109** [comment]
> i can do this in c/c++ if u assign it to me

Hi @parthchainani ! Please go ahead and do so.
