### ISSUE TITLE
Counting Digits of Integer (Java) with Best Time Complexity

### ISSUE THREAD

**Issue by ATRI2107** [aditya109/git-osp-for-beginners#89]
Hey @aditya109 As mentioned in the [issue](https://github.com/aditya109/git-osp-for-beginners/issues/39) the program for the above given question had been done in a complecity of O(L) where L is the number of digits in that integer. I have opened a [PR](https://github.com/aditya109/git-osp-for-beginners/pull/88) where I have done the same question in a constant time complexity O(1). Please have a look at it.

**Comment by aditya109** [comment]
Hi @ATRI2107 could you please link your PR here ?
